default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV['DB_POOL'] || 5 %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default
  database: "<%= ENV['DB_NAME'] %>_test"

